# Generated by Django 2.2.1 on 2019-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name1', models.CharField(max_length=50)),
                ('year1', models.IntegerField()),
                ('dept1', models.CharField(max_length=10)),
                ('phone1', models.BigIntegerField()),
                ('name2', models.CharField(max_length=50)),
                ('year2', models.IntegerField()),
                ('dept2', models.CharField(max_length=10)),
                ('phone2', models.BigIntegerField()),
            ],
        ),
    ]
