# Generated by Django 2.2.1 on 2019-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(default='', max_length=100),
        ),
    ]
